apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: my-app-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api:latest  
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: /app/qr_codes
              name: qr-codes-storage
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: qr-codes-storage
          persistentVolumeClaim:
            claimName: qr-codes-pvc
