apiVersion: v1
kind: PersistentVolume
metadata:
  name: qr-codes-pv
  namespace: my-app-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/qr-codes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qr-codes-pvc
  namespace: my-app-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
