apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: my-app-namespace
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
